updated yaml file to support QA branch

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -6,7 +6,7 @@ name: testRigor
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
-    branches: [ "main" ]
+    branches: [ "QA" ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -23,48 +23,48 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-                curl -X POST \
-                  -H 'Content-type: application/json' \
-                  -H 'auth-token: 7fcfdd73-b01a-446a-949a-3fc90e7411a2' \
-                  --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
-                  https://api.testrigor.com/api/v1/apps/PybxPXCt4QxNSnZ3E/retest
-                
+              curl -X POST \
+                -H 'Content-type: application/json' \
+                -H 'auth-token: 53fd83f4-d9f4-44f9-b8a8-490e86934ac5' \
+                --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+                https://api.testrigor.com/api/v1/apps/joYxqWB3qEqwRtpTt/retest
+
+              sleep 10
+
+              while true
+              do
+                echo " "
+                echo "==================================="
+                echo " Checking TestRigor retest"
+                echo "==================================="
+                response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/joYxqWB3qEqwRtpTt/status' -H 'auth-token: 53fd83f4-d9f4-44f9-b8a8-490e86934ac5' -H 'Accept: application/json')
+                code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+                body=$(echo "$response" | sed -n '/{/,/}/p')
+                echo "Status code: " $code
+                echo "Response: " $body
+                case $code in
+                  4*|5*)
+                    # 400 or 500 errors
+                    echo "Error calling API"
+                    exit 1
+                    ;;
+                  200)
+                    # 200: successfully finished
+                    echo "Test finished successfully"
+                    exit 0
+                    ;;
+                  227|228)
+                    # 227: New - 228: In progress
+                    echo "Test is not finished yet"
+                    ;;
+                  230)
+                    # 230: Failed
+                    echo "Test finished but failed"
+                    exit 1
+                    ;;
+                  *)
+                    echo "Unknown status"
+                    exit 1
+                  esac
                 sleep 10
-                
-                while true
-                do
-                  echo " "
-                  echo "==================================="
-                  echo " Checking TestRigor retest"
-                  echo "==================================="
-                  response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/PybxPXCt4QxNSnZ3E/status' -H 'auth-token: 7fcfdd73-b01a-446a-949a-3fc90e7411a2' -H 'Accept: application/json')
-                  code=$(echo "$response" | grep HTTP |  awk '{print $2}')
-                  body=$(echo "$response" | sed -n '/{/,/}/p')
-                  echo "Status code: " $code
-                  echo "Response: " $body
-                  case $code in
-                    4*|5*)
-                      # 400 or 500 errors
-                      echo "Error calling API"
-                      exit 1
-                      ;;
-                    200)
-                      # 200: successfully finished
-                      echo "Test finished successfully"
-                      exit 0
-                      ;;
-                    227|228)
-                      # 227: New - 228: In progress
-                      echo "Test is not finished yet"
-                      ;;
-                    230)
-                      # 230: Failed
-                      echo "Test finished but failed"
-                      exit 1
-                      ;;
-                    *)
-                      echo "Unknown status"
-                      exit 1
-                    esac
-                  sleep 10
-                done
+              done
